const data = {
    products: [
        {
            _id: '1',
            name: 'T-Shirt koceng',
            catergory: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'meme biden',
            catergory: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: '3 cat',
            catergory: 'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'quantum cat',
            catergory: 'Shirts',
            image: '/images/p4.jpg',
            price: 120,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'CC',
            catergory: 'Shirts',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Haku',
            catergory: 'Shirts',
            image: '/images/p6.jpg',
            price: 130,
            brand: 'nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality product',
        },
    ]
}

export default data;